### ISSUE TITLE
CoCoNet example and implementation of overlap

### ISSUE THREAD

**Issue by yetiansh** [parasailteam/coconet#3]
Hi, I've read your paper on arxiv. I found that there's a coconet-example repo and currently the link is invalid. Is that repo the `example` directory under this repo?

I also not very sure about your implementation of overlapped all-reduce and comp operations, which is described in your paper. Does `nccl/src/collectives/device/primitives_computation.h` implement an overlapped kernel for all-reduce and other computation operators? Could you give more details of overlap's implementation? Thanks!

**Comment by siddharth9820** [comment]
Any update on this? I'm also searching for integration with PyTorch as claimed in your paper.

Thanks

**Comment by abhijangda** [comment]
This issue has been fixed but I forgot to close it. You can view the Pytorch integration here: https://github.com/parasailteam/coconet-experiments . Note that the datasets are not available anymore. If you have any questions then please create a new issue
