### ISSUE TITLE
Doubts about experimental performance data of single operator overlap

### ISSUE THREAD

**Issue by lixiaolx** [parasailteam/coconet#8]
![image](https://user-images.githubusercontent.com/17673134/233964699-e8c9ae8f-da08-484e-a01b-2f534f3cc408.png)

I would like to ask whether the 1.36X comparison base in the paper is obtained from the same nccl-channel test?

Or select the optimal value of different channels of cubals+allreduce, and compare the optimal value of different channels of overlap to get 1.36X

**Comment by abhijangda** [comment]
Both CoCoNet and NCCL times are obtained by using the values of NCCL_BUFFSIZE and CHANNELS that performs best. The tile size for cutlass were same. Although it is possible that different tile size for cutlass might have made CoCoNet perform better.
